name: tictac
description: Torpedo Internal Component for Text and Audio Chat. Flutter chat library built on Tinode.
version: 0.1.1
homepage: https://github.com/Play-Bonkers/tictac

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2
  intl: '>=0.17.0 <1.0.0'
  scroll_to_index: ^3.0.1
  fixnum: ^1.1.0
  uuid: ^4.5.1
  rxdart: '>=0.27.1 <1.0.0'
  web_socket_channel: '>=2.1.0 <4.0.0'
  protobuf: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^4.0.0
